# Generated by Django 5.2 on 2025-05-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bio',
            new_name='description',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.TextField(default='Pozytywny'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(max_length=100),
        ),
    ]
