# Generated by Django 5.2 on 2025-05-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_bio_author_description_review_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='opinion',
        ),
    ]
