# Generated by Django 5.2 on 2025-04-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
