# Generated by Django 5.2 on 2025-05-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_rating_review_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='opinion',
        ),
        migrations.AddField(
            model_name='book',
            name='opinion',
            field=models.TextField(default='Pozytywny'),
        ),
    ]
