# Generated by Django 5.2 on 2025-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_review_opinion_book_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='opinion',
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
